### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by tbicr** [omniscale/imposm-parser#11]
It will be great add python 3 support. I think enough add 3.3+ support.

**Comment by tpievila** [comment]
@tbicr: Working port available at https://github.com/tpievila/imposm-parser. If you find any problems, I'd appreciate any feedback.

**Comment by danvk** [comment]
@hukka did you take down that repo?

**Comment by hukka** [comment]
@danvk I'm afraid I did. I was doing some spring cleaning, and thought that nobody was really interested in it, given the lack of activity. You can still catch the changes from https://github.com/HSLdevcom/imposm-parser, though.
