### ISSUE TITLE
parser skips relevant data

### ISSUE THREAD

**Issue by qwiglydee** [omniscale/imposm-parser#16]
"""
nodes and relations with empty tags will not be returned, but ways will be, since they might be needed for building relations.
"""
WHY!?

a Way can contain nodes
http://wiki.openstreetmap.org/wiki/Way

a Relation can contain nodes
http://wiki.openstreetmap.org/wiki/Relation

a Relation can contain other relations
http://wiki.openstreetmap.org/wiki/Relation:boundary

bloody hell

**Comment by olt** [comment]
[imposm.parser distinguishes the OSM Nodes between coords and nodes](http://imposm.org/docs/imposm.parser/latest/concepts.html#types)

Also, please be polite here. imposm.parser comes "AS IS" and you can use something else if you don't like the way it works.
