### ISSUE TITLE
Issue with setup.py

### ISSUE THREAD

**Issue by daanreijnders** [omniscale/imposm-parser#22]
`imposm.parser/setup.py", line 15
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax
`

**Comment by olt** [comment]
You are using Python 3 right? Imposm-parser is only compatible with Python 2. See #20

**Comment by TimMcCauley** [comment]
@olt we are using this outstanding library in several projects at the university, thank you very much. We are depending on python 3.5 in 2 of these projects and thus were wondering if we should/can invest time to make imposm-parser available for python 3.x. Could you possibly give a a really rough guess of how much work there would be to do? Maybe a student can take care of this then and make it available.
