### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by lechup** [omniscale/imposm-parser#23]
Hey!

I've tried to make Python2 and Python3 version (with one code) and I failed - I had some problems with osm.cpp and conditional ifdefs...

I managed to run test suite (through tox) on python3.5 using this code:
https://github.com/lechup/imposm-parser/tree/python3

Which is mainly based on this work:
https://github.com/sidewalklabs/imposm-parser/commit/64150b1335cf1bed00452d3bca2b74b46e7f67fe

Cheers

**Comment by olt** [comment]
Please see #24.

**Comment by TimMcCauley** [comment]
@lechup I tried your fork and it is building on branch `python3` - is it also working for you?

**Comment by lechup** [comment]
@TimMcCauley yeah it's passing all tests on 3.5 but I haven't test it a lot on python3 - check out tox config. You can upload it to pypi as `iposm-parser3` or use it from github repo in Your requirement file.
